const { GoogleGenAI } = require("@google/genai");

/**
 * Service to call Gemini API for clustered responses
 * 
 * @param {Array} responses - Grouped responses based on geolocation
 * @returns {Array} Tasks generated by Gemini
 */
const analyseResponses = async (responses) => {
  try {
    // The client gets the API key from the environment variable GEMINI_API_KEY.
    const ai = new GoogleGenAI({});

    const prompt = `You are a humanitarian data analyst. Analyse these community survey responses 
    and return ONLY a valid JSON array with no markdown formatting. Each object must have:
    - areaName: string
    - urgencyScore: number between 1 and 10
    - category: one of food, medical, shelter, education, water
    - numberOfPeopleAffected: number
    - requiredSkills: array of strings from [medical, education, logistics, construction, counselling]
    - recommendedAction: string
    - reasoning: string
    
    Survey responses: ${JSON.stringify(responses, null, 2)}`;

    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
    });
    
    let text = response.text;
    
    // Clean up Markdown formatting from response if Gemini includes it
    if(text.startsWith('\`\`\`json')){
        text = text.replace(/^\`\`\`json/, '').replace(/\`\`\`$/, '');
    }
    if(text.startsWith('\`\`\`')){
        text = text.replace(/^\`\`\`/, '').replace(/\`\`\`$/, '');
    }
    
    return JSON.parse(text);
  } catch (error) {
    console.error('Error calling Gemini:', error);
    throw new Error('AI Analysis failed.');
  }
};

module.exports = { analyseResponses };
